const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
const K='xiao30_'; // 3.2 keeps the 3.0 storage key so existing data is preserved
let state={library:store.get(K+'library',[]),plans:store.get(K+'plans',[]),income:store.get(K+'income',[]),tasks:store.get(K+'tasks',[false,false,false,false,false]),decisions:store.get(K+'decisions',0),projects:store.get(K+'projects',[]),prompts:store.get(K+'prompts',[]),history:store.get(K+'history',[]),daily:store.get(K+'daily',null)};const names={dashboard:'总览',team:'AI 团队',command:'指挥中心',create:'内容工厂',cover:'封面实验室',imageStudio:'AI 图片工作室',videoStudio:'视频剪辑',daily:'AI 每日管家',analyse:'数据诊断',doctor:'账号医生',batch:'批量流水线',calendar:'内容日历',library:'内容资产库',projects:'项目中心',prompts:'Prompt 收藏夹',history:'历史记录',income:'收入中心',brand:'品牌大脑',settings:'设置'};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}function go(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=names[id]||'Xiao AI Studio';scrollTo(0,0);if(id==='library')renderLibrary();if(id==='calendar')renderPlans();if(id==='income')renderIncome();if(id==='projects')renderProjects();if(id==='prompts')renderPrompts();if(id==='history')renderHistory();if(id==='daily')renderDaily()};$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
$('#today').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(new Date());$('#theme').onclick=()=>{document.body.classList.toggle('dark');store.set(K+'dark',document.body.classList.contains('dark'))};if(store.get(K+'dark',false))document.body.classList.add('dark');
function brand(){return store.get(K+'brand',{name:'小翠',city:'Birmingham, UK',platforms:'小红书、TikTok',topics:'英国生活、英国驾照、餐馆推广、吉娃娃',voice:'真实、自然、说人话，不夸张。',restaurant:'',rules:'不要编造价格、地址、优惠、经历和数据。'})}
async function ai(payload,target,stateId){const e=$(target),s=$(stateId);e.classList.remove('empty');e.innerHTML='<span class="loading">AI 正在处理</span>';if(s)s.textContent='生成中';try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,context:JSON.stringify(brand())})});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');e.textContent=d.text||'没有返回内容';if(s)s.textContent='已完成';addHistory(payload,d.text||'没有返回内容',target);state.decisions++;store.set(K+'decisions',state.decisions);metrics();return d.text}catch(x){e.textContent='生成失败：'+x.message;if(s)s.textContent='失败';toast('生成失败')}}
async function status(){try{const r=await fetch('/api/status'),d=await r.json();$('#apiBadge').textContent=d.configured?'AI 已连接':'尚未配置 API';$('#modelStatus').value=(d.configured?'已连接 · ':'未连接 · ')+(d.model||'')}catch{$('#apiBadge').textContent='连接异常';$('#modelStatus').value='连接异常'}}status();
const taskLabels=['确定今天只做一个核心目标','准备真实素材和数据','生成并人工检查内容','发布或加入内容日历','24小时后记录结果'];function renderTasks(){$('#taskList').innerHTML=taskLabels.map((x,i)=>`<label><input type="checkbox" data-task="${i}" ${state.tasks[i]?'checked':''}><span>${x}</span></label>`).join('');$$('[data-task]').forEach(x=>x.onchange=()=>{state.tasks[+x.dataset.task]=x.checked;store.set(K+'tasks',state.tasks)})}renderTasks();$('#resetTasks').onclick=()=>{state.tasks=[false,false,false,false,false];store.set(K+'tasks',state.tasks);renderTasks()};const advice=['先复盘最近一条内容，再决定下一条，不要只凭感觉删除。','同一次出行至少拆成“路线、花费、避坑”三种内容。','标题负责让人点开，正文负责让人收藏，封面只说一个重点。','没有真实数据时，不要让 AI 编价格和平台规则。'];function daily(){$('#advice').textContent=advice[Math.floor(Math.random()*advice.length)]}daily();$('#refreshAdvice').onclick=daily;
function save(type,text){if(!text||text.includes('会显示'))return toast('暂无内容');state.library.unshift({id:Date.now(),type,text,date:new Date().toLocaleString('zh-CN')});store.set(K+'library',state.library);metrics();recent();toast('已保存')}$$('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($('#'+b.dataset.copy).textContent);toast('已复制')});$$('[data-save]').forEach(b=>b.onclick=()=>save(b.dataset.type,$('#'+b.dataset.save).textContent));
$('#teamRun').onclick=()=>{if(!$('#teamGoal').value.trim())return toast('请填写目标');ai({task:'team',goal:$('#teamGoal').value,material:$('#teamMaterial').value,platform:$('#teamPlatform').value,period:$('#teamPeriod').value},'#teamResult','#teamState')};$('#commandRun').onclick=()=>{if(!$('#commandGoal').value.trim())return toast('请填写目标');ai({task:'command',goal:$('#commandGoal').value,area:$('#commandArea').value,target:$('#commandTarget').value,extra:$('#commandExtra').value},'#commandResult','#commandState')};$('#createRun').onclick=()=>{if(!$('#createTopic').value.trim())return toast('请填写真实素材');ai({task:'create',type:$('#createType').value,topic:$('#createTopic').value,language:$('#createLang').value,tone:$('#createTone').value,goal:$('#createGoal').value,extra:$('#createExtra').value},'#createResult','#createState')};$('#coverRun').onclick=()=>{if(!$('#coverTopic').value.trim())return toast('请填写主题');ai({task:'cover',topic:$('#coverTopic').value,audience:$('#coverAudience').value,style:$('#coverStyle').value,material:$('#coverMaterial').value},'#coverResult','#coverState')};$('#doctorRun').onclick=()=>{if(!$('#doctorProfile').value.trim())return toast('请填写账号信息');ai({task:'doctor',profile:$('#doctorProfile').value,posts:$('#doctorPosts').value,goal:$('#doctorGoal').value},'#doctorResult','#doctorState')};$('#batchRun').onclick=()=>{if(!$('#batchMaterial').value.trim())return toast('请填写素材');ai({task:'batch',material:$('#batchMaterial').value,platform:$('#batchPlatform').value,count:$('#batchCount').value,goal:$('#batchGoal').value},'#batchResult','#batchState')};
let image='';$('#analysisImage').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#fileName').textContent=f.name;const r=new FileReader();r.onload=()=>image=r.result;r.readAsDataURL(f)};$('#analyseRun').onclick=()=>{const m={views:+$('#views').value||0,likes:+$('#likes').value||0,saves:+$('#saves').value||0,comments:+$('#comments').value||0,note:$('#analysisNote').value};if(!image&&!m.views&&!m.note)return toast('上传截图或填写数据');ai({task:'analyse',metrics:m,image},'#analyseResult','#analyseState')};
function recent(){const a=state.library.slice(0,3);$('#recent').innerHTML=a.length?a.map(x=>`<article><small>${x.type} · ${x.date}</small><b>${x.type}</b><span>${x.text.slice(0,80)}${x.text.length>80?'…':''}</span></article>`).join(''):'<p>还没有保存内容。</p>'}function renderLibrary(){const q=$('#librarySearch').value.toLowerCase(),a=state.library.filter(x=>(x.type+x.text).toLowerCase().includes(q));$('#libraryList').innerHTML=a.length?a.map(x=>`<div class="row"><small>${x.date}</small><div><b>${x.type}</b><small>${x.text.slice(0,100)}…</small></div><span>${x.type}</span><div class="rowactions"><button class="soft" data-cl="${x.id}">复制</button><button class="danger" data-dl="${x.id}">删除</button></div></div>`).join(''):'<p>没有内容。</p>';$$('[data-cl]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(state.library.find(x=>x.id==b.dataset.cl).text);toast('已复制')});$$('[data-dl]').forEach(b=>b.onclick=()=>{state.library=state.library.filter(x=>x.id!=b.dataset.dl);store.set(K+'library',state.library);renderLibrary();recent();metrics()})}$('#librarySearch').oninput=renderLibrary;$('#clearLibrary').onclick=()=>{if(confirm('确定清空内容库？')){state.library=[];store.set(K+'library',[]);renderLibrary();recent();metrics()}};
function renderPlans(){$('#planList').innerHTML=state.plans.length?state.plans.map(x=>`<div class="row"><small>${x.date}</small><div><b>${x.title}</b><small>${x.platform}</small></div><span>${x.done?'已发布':'待发布'}</span><div class="rowactions"><button class="soft" data-tp="${x.id}">${x.done?'撤销':'完成'}</button><button class="danger" data-dp="${x.id}">删除</button></div></div>`).join(''):'<p>还没有计划。</p>';$$('[data-tp]').forEach(b=>b.onclick=()=>{let x=state.plans.find(v=>v.id==b.dataset.tp);x.done=!x.done;store.set(K+'plans',state.plans);renderPlans();metrics()});$$('[data-dp]').forEach(b=>b.onclick=()=>{state.plans=state.plans.filter(x=>x.id!=b.dataset.dp);store.set(K+'plans',state.plans);renderPlans();metrics()})}$('#addPlan').onclick=()=>{const title=prompt('内容主题');if(!title)return;state.plans.unshift({id:Date.now(),title,platform:prompt('平台','小红书')||'小红书',date:prompt('发布时间','明天 20:00')||'待定',done:false});store.set(K+'plans',state.plans);renderPlans();metrics()};
function money(n){return '£'+Number(n||0).toFixed(2)}function renderIncome(){const inn=state.income.filter(x=>x.kind==='收入').reduce((s,x)=>s+x.amount,0),out=state.income.filter(x=>x.kind==='支出').reduce((s,x)=>s+x.amount,0);$('#incomeIn').textContent=money(inn);$('#incomeOut').textContent=money(out);$('#incomeNet').textContent=money(inn-out);$('#incomeList').innerHTML=state.income.length?state.income.map(x=>`<div class="row"><small>${x.date}</small><div><b>${x.source}</b><small>${x.note||''}</small></div><span>${x.kind}</span><div class="rowactions"><b>${money(x.amount)}</b><button class="danger" data-di="${x.id}">删除</button></div></div>`).join(''):'<p>还没有记录。</p>';$$('[data-di]').forEach(b=>b.onclick=()=>{state.income=state.income.filter(x=>x.id!=b.dataset.di);store.set(K+'income',state.income);renderIncome();metrics()})}$('#addIncome').onclick=()=>{const kind=prompt('输入“收入”或“支出”','收入');if(!['收入','支出'].includes(kind))return;const amount=Number(prompt('金额（英镑）','0'));if(!amount)return;state.income.unshift({id:Date.now(),kind,amount,source:prompt('来源/用途','小红书')||'其他',note:prompt('备注','')||'',date:new Date().toLocaleDateString('zh-CN')});store.set(K+'income',state.income);renderIncome();metrics()};
function loadBrand(){const b=brand();$('#brandName').value=b.name||'';$('#brandCity').value=b.city||'';$('#brandPlatforms').value=b.platforms||'';$('#brandTopics').value=b.topics||'';$('#brandVoice').value=b.voice||'';$('#brandRestaurant').value=b.restaurant||'';$('#brandRules').value=b.rules||''}loadBrand();$('#saveBrand').onclick=()=>{store.set(K+'brand',{name:$('#brandName').value,city:$('#brandCity').value,platforms:$('#brandPlatforms').value,topics:$('#brandTopics').value,voice:$('#brandVoice').value,restaurant:$('#brandRestaurant').value,rules:$('#brandRules').value});toast('已保存')};
function metrics(){const inn=state.income.filter(x=>x.kind==='收入').reduce((s,x)=>s+x.amount,0),out=state.income.filter(x=>x.kind==='支出').reduce((s,x)=>s+x.amount,0);$('#mLibrary').textContent=state.library.length;$('#mPlans').textContent=state.plans.filter(x=>!x.done).length;$('#mIncome').textContent=money(inn-out);$('#mDecisions').textContent=state.decisions}$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:'3.4',...state,brand:brand()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='xiao-ai-studio-3.4-data.json';a.click();URL.revokeObjectURL(a.href)};metrics();recent();renderIncome();


// Xiao AI Studio 3.1: quick templates and browser draft autosave
const contentTemplates={
 boots:{type:'英国生活攻略',tone:'攻略收藏型',goal:'提高收藏',topic:'我在英国 Boots 看到/购买了这些商品：\n1. 商品名称与价格：\n2. 活动信息：\n3. 我的真实使用感受：\n4. 适合谁、需要注意什么：',extra:'不要编造价格或活动截止日期；信息不确定时标注需要核实。'},
 english:{type:'英国生活攻略',tone:'真实自然',goal:'提高关注',topic:'今天英语学校课堂内容：\n1. 学习主题：\n2. 老师讲的重点：\n3. 我容易犯的错误：\n4. 对英语基础一般的人有什么帮助：',extra:'语言简单自然，适合英语基础一般的读者。'},
 restaurant:{type:'餐馆推广套装',tone:'真实自然',goal:'提高评论',topic:'餐厅本次要推广的内容：\n1. 菜品/活动：\n2. 真实特点：\n3. 价格或优惠（如有）：\n4. 地址、营业时间与预订方式：',extra:'避免夸大，不编造顾客评价；同时生成适合小红书和短视频的版本。'},
 driving:{type:'英国驾照分享',tone:'攻略收藏型',goal:'提高收藏',topic:'我的英国驾照学习/考试经历：\n1. 城市与考点：\n2. 预约方式：\n3. 我遇到的难点：\n4. 通过后最想提醒大家的事：',extra:'涉及考试规则时提醒读者以 DVSA 官方信息为准。'},
 pet:{type:'吉娃娃日常',tone:'轻松有趣',goal:'提高评论',topic:'今天和吉娃娃发生的真实事情：\n1. 场景：\n2. 它做了什么：\n3. 我的反应：\n4. 想问大家的问题：',extra:'不要把普通行为诊断为疾病；健康问题提示咨询兽医。'},
 life:{type:'英国生活攻略',tone:'真实自然',goal:'提高收藏',topic:'这次英国生活分享：\n1. 地点/事情：\n2. 交通或流程：\n3. 实际花费：\n4. 优点、缺点和避坑：',extra:'只使用我提供的真实经历和数据。'}
};
function applyTemplate(key){const t=contentTemplates[key];if(!t)return;go('create');$('#createType').value=t.type;$('#createTone').value=t.tone;$('#createGoal').value=t.goal;$('#createTopic').value=t.topic;$('#createExtra').value=t.extra;saveDraft();$('#createTopic').focus();toast('模板已填写，可继续修改')}
$$('[data-template]').forEach(b=>b.onclick=()=>applyTemplate(b.dataset.template));
const draftFields=['createType','createLang','createTopic','createTone','createGoal','createExtra'];
function saveDraft(){const draft={};draftFields.forEach(id=>draft[id]=$('#'+id)?.value||'');store.set(K+'createDraft',draft);const el=$('#draftStatus');if(el)el.textContent='草稿已自动保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}
function loadDraft(){const d=store.get(K+'createDraft',null);if(!d)return;draftFields.forEach(id=>{if($('#'+id)&&d[id]!==undefined)$('#'+id).value=d[id]});const el=$('#draftStatus');if(el)el.textContent='已恢复上次未完成草稿'}
loadDraft();draftFields.forEach(id=>$('#'+id)?.addEventListener('input',saveDraft));
const originalCreateRun=$('#createRun').onclick;$('#createRun').onclick=()=>{saveDraft();originalCreateRun()};


// Xiao AI Studio 3.2: Project Hub + Prompt Library
let activeProjectId=state.projects[0]?.id||null;
const projectEls={name:$('#projectName'),goal:$('#projectGoal'),platform:$('#projectPlatform'),status:$('#projectStatus'),next:$('#projectNext')};
function blankProjectForm(){Object.values(projectEls).forEach(el=>{if(el)el.value=''});if(projectEls.platform)projectEls.platform.value='小红书';if(projectEls.status)projectEls.status.value='进行中';$('#projectState').textContent='新项目'}
function fillProject(p){if(!p)return blankProjectForm();projectEls.name.value=p.name||'';projectEls.goal.value=p.goal||'';projectEls.platform.value=p.platform||'小红书';projectEls.status.value=p.status||'进行中';projectEls.next.value=p.next||'';$('#projectState').textContent='最后更新：'+(p.updated||'刚刚')}
function renderProjects(){const list=$('#projectList');if(!list)return;list.innerHTML=state.projects.length?state.projects.map(p=>`<button class="project-item ${p.id===activeProjectId?'active':''}" data-project="${p.id}"><span>${p.status}</span><b>${p.name||'未命名项目'}</b><small>${p.platform||''}</small><em>${p.next||'还没有下一步'}</em></button>`).join(''):'<div class="empty-state"><b>还没有项目</b><small>先创建“英国生活”“餐厅推广”或“英语学习”项目。</small></div>';$$('[data-project]').forEach(b=>b.onclick=()=>{activeProjectId=Number(b.dataset.project);fillProject(state.projects.find(p=>p.id===activeProjectId));renderProjects()});if(activeProjectId)fillProject(state.projects.find(p=>p.id===activeProjectId))}
$('#addProject').onclick=()=>{activeProjectId=null;blankProjectForm();$('#projectName').focus()};
$('#saveProject').onclick=()=>{const name=projectEls.name.value.trim();if(!name)return toast('请填写项目名称');const data={name,goal:projectEls.goal.value.trim(),platform:projectEls.platform.value,status:projectEls.status.value,next:projectEls.next.value.trim(),updated:new Date().toLocaleString('zh-CN')};if(activeProjectId){const i=state.projects.findIndex(p=>p.id===activeProjectId);state.projects[i]={...state.projects[i],...data}}else{activeProjectId=Date.now();state.projects.unshift({id:activeProjectId,...data})}store.set(K+'projects',state.projects);renderProjects();toast('项目已保存')};
$('#deleteProject').onclick=()=>{if(!activeProjectId)return toast('请先选择项目');if(!confirm('确定删除这个项目？'))return;state.projects=state.projects.filter(p=>p.id!==activeProjectId);activeProjectId=state.projects[0]?.id||null;store.set(K+'projects',state.projects);activeProjectId?fillProject(state.projects[0]):blankProjectForm();renderProjects();toast('项目已删除')};

function renderPrompts(){const box=$('#promptList');if(!box)return;const q=($('#promptSearch').value||'').toLowerCase(),cat=$('#promptCategory').value;const items=state.prompts.filter(p=>(!cat||p.category===cat)&&(`${p.name} ${p.category} ${p.text}`.toLowerCase().includes(q)));box.innerHTML=items.length?items.map(p=>`<article class="prompt-card"><div><span>${p.category}</span><b>${p.name}</b></div><p>${p.text.slice(0,160)}${p.text.length>160?'…':''}</p><div><button class="soft small" data-use-prompt="${p.id}">带入创作</button><button class="icon small" data-copy-prompt="${p.id}">复制</button><button class="danger small" data-delete-prompt="${p.id}">删除</button></div></article>`).join(''):'<div class="empty-state"><b>还没有 Prompt</b><small>保存常用写作要求后，可以一键带入内容工厂。</small></div>';$$('[data-use-prompt]').forEach(b=>b.onclick=()=>{const p=state.prompts.find(x=>x.id==b.dataset.usePrompt);go('create');$('#createExtra').value=p.text;saveDraft();toast('已带入内容工厂')});$$('[data-copy-prompt]').forEach(b=>b.onclick=async()=>{const p=state.prompts.find(x=>x.id==b.dataset.copyPrompt);await navigator.clipboard.writeText(p.text);toast('已复制')});$$('[data-delete-prompt]').forEach(b=>b.onclick=()=>{state.prompts=state.prompts.filter(x=>x.id!=b.dataset.deletePrompt);store.set(K+'prompts',state.prompts);renderPrompts();toast('已删除')})}
$('#addPrompt').onclick=()=>{const name=prompt('Prompt 名称','小红书真实攻略');if(!name)return;const category=prompt('分类：小红书 / TikTok / 餐厅 / 英语学习 / 英国生活 / 其他','小红书')||'其他';const text=prompt('请输入 Prompt 内容','请根据我的真实经历，生成自然、不夸张、适合收藏的小红书文案。不要编造价格、地址或数据。');if(!text)return;state.prompts.unshift({id:Date.now(),name,category,text,date:new Date().toLocaleString('zh-CN')});store.set(K+'prompts',state.prompts);renderPrompts();toast('Prompt 已保存')};
$('#promptSearch').oninput=renderPrompts;$('#promptCategory').onchange=renderPrompts;
renderProjects();renderPrompts();


// Xiao AI Studio 3.3: automatic AI history
const historyTaskNames={team:'AI 团队方案',command:'AI 决策',create:'内容创作',cover:'封面方案',analyse:'数据诊断',doctor:'账号体检',batch:'批量内容方案'};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function historyInput(payload){const copy={...payload};delete copy.image;delete copy.context;return copy}
function historyTitle(payload){const raw=payload.goal||payload.topic||payload.material||payload.profile||payload.note||historyTaskNames[payload.task]||'AI 记录';return String(raw).replace(/\s+/g,' ').trim().slice(0,46)||historyTaskNames[payload.task]||'AI 记录'}
function addHistory(payload,result,target){const item={id:Date.now(),task:payload.task||'other',type:historyTaskNames[payload.task]||'AI 记录',title:historyTitle(payload),input:historyInput(payload),result:String(result||''),target:String(target||''),date:new Date().toLocaleString('zh-CN'),timestamp:Date.now()};state.history.unshift(item);state.history=state.history.slice(0,200);store.set(K+'history',state.history);}
function renderHistory(){const box=$('#historyList');if(!box)return;const q=($('#historySearch').value||'').toLowerCase();const cat=$('#historyType').value;const items=state.history.filter(h=>(!cat||h.task===cat)&&(`${h.title} ${h.type} ${h.result} ${JSON.stringify(h.input)}`.toLowerCase().includes(q)));box.innerHTML=items.length?items.map(h=>`<article class="history-card"><div class="history-meta"><span>${esc(h.type)}</span><small>${esc(h.date)}</small></div><h3>${esc(h.title)}</h3><p>${esc(h.result.slice(0,220))}${h.result.length>220?'…':''}</p><div class="history-actions"><button class="primary small" data-open-history="${h.id}">查看</button><button class="soft small" data-copy-history="${h.id}">复制结果</button><button class="soft small" data-continue-history="${h.id}">继续创作</button><button class="danger small" data-delete-history="${h.id}">删除</button></div></article>`).join(''):'<div class="empty-state"><b>还没有历史记录</b><small>AI 每次成功生成后，会自动保存在当前浏览器。</small></div>';
$$('[data-open-history]').forEach(b=>b.onclick=()=>openHistory(Number(b.dataset.openHistory)));
$$('[data-copy-history]').forEach(b=>b.onclick=async()=>{const h=state.history.find(x=>x.id==b.dataset.copyHistory);if(!h)return;await navigator.clipboard.writeText(h.result);toast('结果已复制')});
$$('[data-continue-history]').forEach(b=>b.onclick=()=>continueHistory(Number(b.dataset.continueHistory)));
$$('[data-delete-history]').forEach(b=>b.onclick=()=>{state.history=state.history.filter(x=>x.id!=b.dataset.deleteHistory);store.set(K+'history',state.history);renderHistory();toast('历史记录已删除')});}
function openHistory(id){const h=state.history.find(x=>x.id===id);if(!h)return;$('#historyDetailTitle').textContent=h.title;$('#historyDetailMeta').textContent=`${h.type} · ${h.date}`;$('#historyDetailInput').textContent=JSON.stringify(h.input,null,2);$('#historyDetailResult').textContent=h.result;$('#historyModal').classList.add('show')}
function closeHistory(){ $('#historyModal').classList.remove('show') }
function continueHistory(id){const h=state.history.find(x=>x.id===id);if(!h)return;const p=h.input||{};if(h.task==='create'){go('create');if(p.type)$('#createType').value=p.type;if(p.topic)$('#createTopic').value=p.topic;if(p.language)$('#createLang').value=p.language;if(p.tone)$('#createTone').value=p.tone;if(p.goal)$('#createGoal').value=p.goal;if(p.extra)$('#createExtra').value=p.extra;$('#createResult').textContent=h.result;$('#createResult').classList.remove('empty');saveDraft()}else{go('command');$('#commandGoal').value=`继续完善这份${h.type}：\n${h.result}`;$('#commandExtra').value='请保留有用内容，并给出更具体、可执行的下一步。'}toast('已恢复，可继续修改')}
$('#historySearch').oninput=renderHistory;$('#historyType').onchange=renderHistory;$('#clearHistory').onclick=()=>{if(confirm('确定清空全部 AI 历史记录？此操作无法撤销。')){state.history=[];store.set(K+'history',[]);renderHistory();toast('历史记录已清空')}};
$('#closeHistory').onclick=closeHistory;$('#historyModal').onclick=e=>{if(e.target.id==='historyModal')closeHistory()};
renderHistory();

// Xiao AI Studio 3.4: AI Image Studio
let studioOriginal=null,studioImageData='',blurMode=false,blurRects=[],dragStart=null;
const canvas=$('#studioCanvas'),ctx=canvas?.getContext('2d');
function readStudioFile(file){if(!file)return;if(!file.type.startsWith('image/'))return toast('请选择图片文件');$('#studioFileName').textContent=file.name;const r=new FileReader();r.onload=()=>{studioImageData=r.result;const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/img.width,max/img.height);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);studioOriginal=img;blurRects=[];drawStudio();canvas.style.display='block';$('#canvasEmpty').style.display='none'};img.src=r.result};r.readAsDataURL(file)}
$('#studioFile').onchange=e=>readStudioFile(e.target.files[0]);
const drop=$('.image-drop');['dragenter','dragover'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop?.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop?.addEventListener('drop',e=>readStudioFile(e.dataTransfer.files[0]));
function drawStudio(){if(!studioOriginal||!ctx)return;const b=$('#imgBrightness').value,c=$('#imgContrast').value,s=$('#imgSaturation').value;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.filter=`brightness(${b}%) contrast(${c}%) saturate(${s}%)`;ctx.drawImage(studioOriginal,0,0,canvas.width,canvas.height);ctx.filter='none';blurRects.forEach(r=>pixelate(r))}
function pixelate(r){const x=Math.max(0,Math.min(r.x,r.x+r.w)),y=Math.max(0,Math.min(r.y,r.y+r.h)),w=Math.min(canvas.width-x,Math.abs(r.w)),h=Math.min(canvas.height-y,Math.abs(r.h));if(w<2||h<2)return;const size=14,sw=Math.max(1,Math.round(w/size)),sh=Math.max(1,Math.round(h/size));const off=document.createElement('canvas');off.width=sw;off.height=sh;const o=off.getContext('2d');o.imageSmoothingEnabled=false;o.drawImage(canvas,x,y,w,h,0,0,sw,sh);ctx.imageSmoothingEnabled=false;ctx.drawImage(off,0,0,sw,sh,x,y,w,h);ctx.imageSmoothingEnabled=true}
['imgBrightness','imgContrast','imgSaturation'].forEach(id=>$('#'+id).oninput=drawStudio);
$('#resetImage').onclick=()=>{['imgBrightness','imgContrast','imgSaturation'].forEach(id=>$('#'+id).value=100);blurRects=[];drawStudio();toast('图片效果已重置')};
$('#toggleBlur').onclick=()=>{blurMode=!blurMode;$('#toggleBlur').textContent=blurMode?'关闭手动打码':'开启手动打码';toast(blurMode?'请在图片上拖动框选':'手动打码已关闭')};
function canvasPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas?.addEventListener('pointerdown',e=>{if(!blurMode||!studioOriginal)return;dragStart=canvasPoint(e);canvas.setPointerCapture(e.pointerId)});canvas?.addEventListener('pointerup',e=>{if(!dragStart)return;const p=canvasPoint(e);blurRects.push({x:dragStart.x,y:dragStart.y,w:p.x-dragStart.x,h:p.y-dragStart.y});dragStart=null;drawStudio()});
function downloadCanvas(c,name,quality=.85){c.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',quality)}
$('#downloadImage').onclick=()=>{if(!studioOriginal)return toast('请先上传图片');downloadCanvas(canvas,'xiao-ai-image.jpg',+$('#imgQuality').value/100)};
$('#nineGrid').onclick=()=>{if(!studioOriginal)return toast('请先上传图片');for(let row=0;row<3;row++)for(let col=0;col<3;col++){const c=document.createElement('canvas');c.width=Math.floor(canvas.width/3);c.height=Math.floor(canvas.height/3);c.getContext('2d').drawImage(canvas,col*c.width,row*c.height,c.width,c.height,0,0,c.width,c.height);setTimeout(()=>downloadCanvas(c,`xiao-grid-${row*3+col+1}.jpg`,.92),(row*3+col)*180)}toast('正在生成 9 张图片')};
async function imageAI(mode){if(!studioImageData)return toast('请先上传图片');const question=$('#imageQuestion').value.trim()|| (mode==='ocr'?'提取图片中的全部可见文字，按原顺序整理；再检查姓名、地址、电话、邮箱、二维码、条形码等隐私信息，并给出打码建议。':'分析图片的构图、清晰度、配色、信息重点和是否适合小红书发布，给出具体修改建议。');$('#imageAiResult').textContent='AI 正在识别...';$('#imageAiResult').classList.remove('empty');await ai({task:'imageStudio',mode,question,image:studioImageData},'#imageAiResult',null)}
$('#imageOcr').onclick=()=>imageAI('ocr');$('#imageAnalyse').onclick=()=>imageAI('analyse');
$('#generateImage').onclick=async()=>{const prompt=$('#imagePrompt').value.trim();if(!prompt)return toast('请输入图片描述');const box=$('#generatedImage');box.textContent='AI 正在生成图片...';box.classList.remove('empty');try{const r=await fetch('/api/image-generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt})});const d=await r.json();if(!r.ok)throw Error(d.error||'生成失败');box.innerHTML=`<img src="${d.image}" alt="AI generated"><button class="soft full" id="saveGenerated">保存图片</button>`;$('#saveGenerated').onclick=()=>{const a=document.createElement('a');a.href=d.image;a.download='xiao-ai-generated.png';a.click()}}catch(e){box.textContent='生成失败：'+e.message}};

// Xiao AI Studio 3.4: AI Daily Assistant
function dailyKey(){return new Date().toISOString().slice(0,10)}
function ensureDaily(){const key=dailyKey();if(!state.daily||state.daily.date!==key){state.daily={date:key,tasks:[{id:1,text:'完成一条可发布内容',done:false},{id:2,text:'整理今天的图片素材',done:false},{id:3,text:'检查一个未完成草稿',done:false}]};store.set(K+'daily',state.daily)}return state.daily}
function renderDaily(){const d=ensureDaily(),box=$('#dailyTaskList');if(!box)return;$('#dailyDate').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(new Date());box.innerHTML=d.tasks.length?d.tasks.map(t=>`<label class="daily-task ${t.done?'done':''}"><input type="checkbox" data-daily-check="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}</span><button class="danger small" data-daily-delete="${t.id}">删除</button></label>`).join(''):'<div class="empty-state"><b>今天还没有任务</b><small>点击右上角添加。</small></div>';const done=d.tasks.filter(t=>t.done).length,p=d.tasks.length?Math.round(done/d.tasks.length*100):0;$('#dailyProgress').style.width=p+'%';$('#dailyProgressText').textContent=`${p}% 完成 · ${done}/${d.tasks.length}`;$$('[data-daily-check]').forEach(x=>x.onchange=()=>{const t=d.tasks.find(v=>v.id==x.dataset.dailyCheck);t.done=x.checked;store.set(K+'daily',d);renderDaily()});$$('[data-daily-delete]').forEach(x=>x.onclick=e=>{e.preventDefault();d.tasks=d.tasks.filter(v=>v.id!=x.dataset.dailyDelete);store.set(K+'daily',d);renderDaily()});renderDailySuggestion()}
function renderDailySuggestion(){const suggestions=[];const draft=store.get(K+'createDraft',null);if(draft?.createTopic?.trim())suggestions.push('你有一份未完成的内容草稿，今天可以先继续修改并完成。');const active=state.projects.filter(p=>p.status==='进行中');if(active.length)suggestions.push(`你有 ${active.length} 个进行中的项目，优先推进“${active[0].name}”。`);if(state.plans.some(p=>!p.done))suggestions.push(`内容日历里还有 ${state.plans.filter(p=>!p.done).length} 条待发布计划。`);suggestions.push('今天只完成一个核心目标，比同时开始很多任务更有效。','先整理真实照片和花费，再让 AI 写文案，可以减少错误。');$('#dailySuggestion').textContent=suggestions[Math.floor(Math.random()*suggestions.length)]}
$('#addDailyTask').onclick=()=>{const text=prompt('今天要完成什么？');if(!text)return;const d=ensureDaily();d.tasks.push({id:Date.now(),text,done:false});store.set(K+'daily',d);renderDaily()};$('#resetDaily').onclick=()=>{const d=ensureDaily();d.tasks.forEach(t=>t.done=false);store.set(K+'daily',d);renderDaily()};$('#refreshDailySuggestion').onclick=renderDailySuggestion;renderDaily();


// Xiao AI Studio 3.4: Local Video Studio
let videoObjectUrl='', videoFileData=null, previewTimer=null, exportingVideo=false;
const videoPreview=$('#videoPreview'), videoCanvas=$('#videoCanvas');
function formatVideoTime(seconds){seconds=Math.max(0,Number(seconds)||0);const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function updateTrimSummary(){if(!videoPreview)return;let start=Math.max(0,Number($('#trimStart').value)||0),end=Math.min(videoPreview.duration||0,Number($('#trimEnd').value)||0);if(end<start)end=start;$('#trimSummary').textContent=`${formatVideoTime(start)} — ${formatVideoTime(end)} · ${Math.max(0,end-start).toFixed(1)}秒`}
function loadVideoFile(file){if(!file)return;if(!file.type.startsWith('video/'))return toast('请选择视频文件');if(exportingVideo)return toast('请等待当前导出完成');videoFileData=file;if(videoObjectUrl)URL.revokeObjectURL(videoObjectUrl);videoObjectUrl=URL.createObjectURL(file);videoPreview.src=videoObjectUrl;videoPreview.style.display='block';$('#videoEmpty').style.display='none';$('#videoFileName').textContent=`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`;$('#videoStatus').textContent='正在读取视频信息…';videoPreview.onloadedmetadata=()=>{$('#trimStart').value='0';$('#trimEnd').value=videoPreview.duration.toFixed(1);$('#trimStart').max=$('#trimEnd').max=videoPreview.duration;videoPreview.playbackRate=Number($('#videoSpeed').value);updateTrimSummary();$('#videoStatus').textContent=`视频时长 ${formatVideoTime(videoPreview.duration)}，可以开始剪辑。`}}
$('#videoFile').onchange=e=>loadVideoFile(e.target.files[0]);
const videoDrop=$('.video-drop');['dragenter','dragover'].forEach(ev=>videoDrop?.addEventListener(ev,e=>{e.preventDefault();videoDrop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>videoDrop?.addEventListener(ev,e=>{e.preventDefault();videoDrop.classList.remove('drag')}));videoDrop?.addEventListener('drop',e=>loadVideoFile(e.dataTransfer.files[0]));
['trimStart','trimEnd'].forEach(id=>$('#'+id).oninput=updateTrimSummary);
$('#videoSpeed').onchange=()=>{videoPreview.playbackRate=Number($('#videoSpeed').value)};
$('#setTrimStart').onclick=()=>{if(!videoFileData)return toast('请先上传视频');$('#trimStart').value=videoPreview.currentTime.toFixed(1);if(Number($('#trimEnd').value)<videoPreview.currentTime)$('#trimEnd').value=videoPreview.currentTime.toFixed(1);updateTrimSummary()};
$('#setTrimEnd').onclick=()=>{if(!videoFileData)return toast('请先上传视频');$('#trimEnd').value=videoPreview.currentTime.toFixed(1);if(Number($('#trimStart').value)>videoPreview.currentTime)$('#trimStart').value=videoPreview.currentTime.toFixed(1);updateTrimSummary()};
$('#previewTrim').onclick=async()=>{if(!videoFileData)return toast('请先上传视频');clearInterval(previewTimer);const start=Number($('#trimStart').value),end=Number($('#trimEnd').value);if(end<=start)return toast('结束时间必须晚于开始时间');videoPreview.currentTime=start;videoPreview.playbackRate=Number($('#videoSpeed').value);await videoPreview.play();previewTimer=setInterval(()=>{if(videoPreview.currentTime>=end){videoPreview.pause();clearInterval(previewTimer)}},80)};
$('#resetVideo').onclick=()=>{if(!videoFileData)return;clearInterval(previewTimer);videoPreview.pause();videoPreview.currentTime=0;$('#trimStart').value=0;$('#trimEnd').value=videoPreview.duration.toFixed(1);$('#videoRatio').value='source';$('#videoSpeed').value='1';$('#videoMute').checked=false;videoPreview.playbackRate=1;$('#videoProgress').style.width='0%';updateTrimSummary();toast('视频设置已重置')};
function videoOutputSize(){const ratio=$('#videoRatio').value,w=videoPreview.videoWidth,h=videoPreview.videoHeight,max=1080;if(ratio==='source'){const scale=Math.min(1,max/Math.max(w,h));return [Math.round(w*scale),Math.round(h*scale)]}if(ratio==='9:16')return [720,1280];if(ratio==='1:1')return [1080,1080];return [1280,720]}
function drawVideoFrame(context,w,h){const sw=videoPreview.videoWidth,sh=videoPreview.videoHeight,target=w/h,source=sw/sh;let sx=0,sy=0,cw=sw,ch=sh;if(source>target){cw=sh*target;sx=(sw-cw)/2}else if(source<target){ch=sw/target;sy=(sh-ch)/2}context.drawImage(videoPreview,sx,sy,cw,ch,0,0,w,h)}
$('#captureCover').onclick=()=>{if(!videoFileData||!videoPreview.videoWidth)return toast('请先上传视频');const [w,h]=videoOutputSize(),c=document.createElement('canvas');c.width=w;c.height=h;drawVideoFrame(c.getContext('2d'),w,h);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='xiao-video-cover.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')};
$('#exportVideo').onclick=async()=>{if(!videoFileData)return toast('请先上传视频');if(exportingVideo)return toast('视频正在导出');if(!window.MediaRecorder||!videoCanvas.captureStream)return toast('当前浏览器不支持本地视频导出，请使用最新版 Chrome 或 Edge');const start=Number($('#trimStart').value),end=Number($('#trimEnd').value),speed=Number($('#videoSpeed').value);if(!(end>start))return toast('请选择有效的剪辑时间');const [w,h]=videoOutputSize(),context=videoCanvas.getContext('2d');videoCanvas.width=w;videoCanvas.height=h;exportingVideo=true;$('#exportVideo').disabled=true;$('#videoStatus').textContent='正在准备导出，请不要关闭页面…';$('#videoProgress').style.width='0%';videoPreview.pause();videoPreview.currentTime=start;await new Promise(resolve=>videoPreview.addEventListener('seeked',resolve,{once:true}));videoPreview.playbackRate=speed;
let stream=videoCanvas.captureStream(30),audioContext=null;if(!$('#videoMute').checked){try{audioContext=new (window.AudioContext||window.webkitAudioContext)();const source=audioContext.createMediaElementSource(videoPreview),dest=audioContext.createMediaStreamDestination();source.connect(dest);source.connect(audioContext.destination);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t))}catch(e){console.warn('Audio export unavailable',e)}}
const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'';const recorder=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:5000000}:undefined),chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='xiao-video-edit.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);exportingVideo=false;$('#exportVideo').disabled=false;$('#videoProgress').style.width='100%';$('#videoStatus').textContent='导出完成，视频已开始下载。';audioContext?.close();toast('视频导出完成')};recorder.start(500);await videoPreview.play();let raf=0;const render=()=>{drawVideoFrame(context,w,h);const progress=Math.min(1,(videoPreview.currentTime-start)/(end-start));$('#videoProgress').style.width=(progress*100).toFixed(1)+'%';$('#videoStatus').textContent=`正在导出 ${Math.round(progress*100)}%`;if(videoPreview.currentTime>=end||videoPreview.ended){videoPreview.pause();cancelAnimationFrame(raf);if(recorder.state!=='inactive')recorder.stop();return}raf=requestAnimationFrame(render)};render()};
